import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data } = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>FARDEV.stock-manager</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>
          <div>{data ? <p>{data.greeting}</p> : <p>Loading...</p>}</div>
        </div>
      </div>
    </>
  );
};

export default Home;

// type TechnologyCardProps = {
//   name: string;
//   description: string;
//   documentation: string;
// };

// const TechnologyCard = ({
//   name,
//   description,
//   documentation,
// }: TechnologyCardProps) => {
//   return (
//     <section>
//       <h2>{name}</h2>
//       <p>{description}</p>
//       <a href={documentation} target="_blank" rel="noreferrer">
//         Documentation
//       </a>
//     </section>
//   );
// };
